version: "3"
services:
  nginx:
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: nginx:${NGINX_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTP_HOST_PORT_9000}:9001"
      - "${NGINX_HTTP_HOST_PORT_9002}:9002"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - default
      # 可以把-default 改成下列配置，以固定容器IP
      #default:
      #  ipv4_address: 10.0.0.10
  # php:
  #   build:
  #     context: ./services/php
  #     args:
  #       PHP_VERSION: php:${PHP_VERSION}-fpm-alpine
  #       CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
  #       PHP_EXTENSIONS: ${PHP_EXTENSIONS}
  #       TZ: "$TZ"
  #   container_name: php
  #   expose:
  #     - 9501
  #   volumes:
  #     - ${SOURCE_DIR}:/www/:rw
  #     - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
  #     - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
  #     - ${PHP_LOG_DIR}:/var/log/php
  #     - ${DATA_DIR}/composer:/tmp/composer
  #   restart: always
  #   cap_add:
  #     - SYS_PTRACE
  #   networks:
  #     - default
  php80:
    build:
      context: ./services/php80
      args:
        PHP_VERSION: php:${PHP80_VERSION}-fpm-alpine3.17
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP80_EXTENSIONS}
        TZ: "$TZ"
    container_name: php80
    expose:
      - 9501
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP80_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP80_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP80_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${DATA_DIR}/redis:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: "$TZ"
    networks:
      - default

  # mysql5:
  #   image: mysql/mysql-server:${MYSQL5_VERSION}
  #   container_name: mysql5
  #   ports:
  #     - "${MYSQL5_HOST_PORT}:3306"
  #   volumes:
  #     - ${MYSQL5_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
  #     - ${DATA_DIR}/mysql5:/var/lib/mysql/:rw
  #     - ${MYSQL5_LOG_DIR}:/var/log/mysql/:rw
  #   restart: always
  #   networks:
  #     - default
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "${MYSQL5_ROOT_PASSWORD}"
  #     MYSQL_ROOT_HOST: "${MYSQL5_ROOT_HOST}"
  #     TZ: "$TZ"

  # elasticsearch:
  #   build:
  #     context: ./services/elasticsearch
  #     args:
  #       ELASTICSEARCH_VERSION: ${ELASTICSEARCH_VERSION}
  #       ELASTICSEARCH_PLUGINS: ${ELASTICSEARCH_PLUGINS}
  #   container_name: elasticsearch
  #   environment:
  #     - TZ=$TZ
  #     - discovery.type=single-node
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   volumes:
  #     - ${DATA_DIR}/esdata:/usr/share/elasticsearch/data
  #     - ${ELASTICSEARCH_CONF_FILE}:/usr/share/elasticsearch/config/elasticsearch.yml
  #   hostname: elasticsearch
  #   restart: always
  #   ports:
  #     - "${ELASTICSEARCH_HOST_PORT_C}:9200"
  #     - "${ELASTICSEARCH_HOST_PORT_S}:9300"

  # kibana:
  #   image: kibana:${KIBANA_VERSION}
  #   container_name: kibana
  #   environment:
  #     TZ: "$TZ"
  #     elasticsearch.hosts: http://elasticsearch:9200
  #     I18N_LOCALE: "${KIBANA_I18N_LOCALE}"
  #   hostname: kibana
  #   depends_on:
  #     - elasticsearch
  #   restart: always
  #   ports:
  #     - "${KIBANA_HOST}:5601"

  # logstash:
  #   image: logstash:${LOGSTASH_VERSION}
  #   container_name: logstash
  #   hostname: logstash
  #   volumes:
  #     - ${SOURCE_DIR}/plexins2.0/storage/logs:/usr/share/logstash/logs
  #   restart: always
  #   depends_on:
  #     - elasticsearch
  #   environment:
  #     TZ: "$TZ"
  #   ports:
  #     - "${LOGSTASH_HOST_PORT_C}:9600"
  #     - "${LOGSTASH_HOST_PORT_S}:5044"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      # 解除下面的注释可以设置网段，用于nginx等容器固定容器IP
      #config:
      #  - subnet: 10.0.0.0/24